name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        registry: argus.azurecr.io
        username: argus
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Build Docker Image and optionally push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/backend.Dockerfile
        push: true
        cache-from: type=registry,ref=argus.azurecr.io/argus-backend:latest
        tags: |
          argus.azurecr.io/argus-backend:latest
          argus.azurecr.io/argus-backend:${{ steps.date.outputs.date }}_${{ github.run_number }}
